services:
  motioneye:
    image: ccrisan/motioneye:master-armhf
    container_name: motioneye
    restart: always
    ports:
      - "8765:8765"
      - "8081:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
      # Configuration for 1st camera - we will have one camera per child.
      - ./camera.conf:/etc/motioneye/camera-1.conf
    devices:
      - /dev/video0:/dev/video0

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: <CHILD_HOSTNAME> # This will be the name of the child in the tailnet
    environment:
      - TS_AUTHKEY=<TAILSCALE_AUTH_KEY>
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped