networks:
  proxynet:
    driver: bridge

volumes:
  tailscale-state:

services:
  motioneye:
    image: ccrisan/motioneye:master-armhf
    container_name: motioneye
    restart: always
    # Uncomment this for debugging purpose or if you you are not using public domain.
    # ports:
    #   - "8765:8765"
    #   - "8081:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
    networks:
      - proxynet

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
      - /var/lib/ntfy:/var/lib/ntfy
    environment:
      NTFY_BASE_URL: <THIS_SERVICE_PUBLIC_URL>
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh # This is for fixing the push notifications for IOS, don't worry, this doesn't mean our messages will go through ntfy server.
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
    # Uncomment this for debugging purpose or if you you are not using public domain.
    # ports:
    #   - 8080:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8080/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    networks:
      - proxynet

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token <TOKEN>
    networks:
      - proxynet
  
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale-mothership
    hostname: <MOTHERSHIP_HOSTNAME> # This will be the name of the mothership in the tailnet
    environment:
      - TS_AUTHKEY=<TAILSCALE_AUTH_KEY>
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped